<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>syncai_dwb_controller</name>
  <version>0.0.0</version>
  <description>DWB local planner ported from nav2: dwb_core, dwb_plugins, dwb_critics, nav_2d_utils and costmap_queue merged into one package</description>
  <maintainer email="chungweeeei@gmail.com">ros</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>angles</depend>
  <depend>builtin_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>syncai_costmap_2d</depend>
  <depend>syncai_dwb_msgs</depend>
  <depend>syncai_nav_core</depend>
  <depend>syncai_util</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <syncai_nav_core plugin="${prefix}/controller_plugin.xml" />
    <syncai_dwb_controller plugin="${prefix}/dwb_plugins.xml" />
  </export>
</package>
