[patch.crates-io.syncai_robot_state]
path = "/home/ubuntu/robot_ws/install/syncai_robot_state/share/syncai_robot_state/rust"

[patch.crates-io.syncai_common]
path = "/home/ubuntu/robot_ws/install/syncai_common/share/syncai_common/rust"

[patch.crates-io.visualization_msgs]
path = "/opt/ros/humble/share/visualization_msgs/rust"

[patch.crates-io.test_msgs]
path = "/opt/ros2_rust_ws/install/test_msgs/share/test_msgs/rust"

[patch.crates-io.examples_rclrs_worker_demo]
path = "/opt/ros2_rust_ws/install/examples_rclrs_worker_demo/share/examples_rclrs_worker_demo/rust"

[patch.crates-io.examples_rclrs_parameter_demo]
path = "/opt/ros2_rust_ws/install/examples_rclrs_parameter_demo/share/examples_rclrs_parameter_demo/rust"

[patch.crates-io.examples_rclrs_minimal_pub_sub]
path = "/opt/ros2_rust_ws/install/examples_rclrs_minimal_pub_sub/share/examples_rclrs_minimal_pub_sub/rust"

[patch.crates-io.examples_rclrs_minimal_client_service]
path = "/opt/ros2_rust_ws/install/examples_rclrs_minimal_client_service/share/examples_rclrs_minimal_client_service/rust"

[patch.crates-io.examples_rclrs_logging_demo]
path = "/opt/ros2_rust_ws/install/examples_rclrs_logging_demo/share/examples_rclrs_logging_demo/rust"

[patch.crates-io.example_interfaces]
path = "/opt/ros2_rust_ws/install/example_interfaces/share/example_interfaces/rust"

[patch.crates-io.action_msgs]
path = "/opt/ros/humble/share/action_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/opt/ros/humble/share/unique_identifier_msgs/rust"

[patch.crates-io.trajectory_msgs]
path = "/opt/ros/humble/share/trajectory_msgs/rust"

[patch.crates-io.stereo_msgs]
path = "/opt/ros/humble/share/stereo_msgs/rust"

[patch.crates-io.std_srvs]
path = "/opt/ros/humble/share/std_srvs/rust"

[patch.crates-io.shape_msgs]
path = "/opt/ros/humble/share/shape_msgs/rust"

[patch.crates-io.sensor_msgs]
path = "/opt/ros/humble/share/sensor_msgs/rust"

[patch.crates-io.rust_pubsub]
path = "/opt/ros2_rust_ws/install/rust_pubsub/share/rust_pubsub/rust"

[patch.crates-io.nav_msgs]
path = "/opt/ros/humble/share/nav_msgs/rust"

[patch.crates-io.diagnostic_msgs]
path = "/opt/ros/humble/share/diagnostic_msgs/rust"

[patch.crates-io.geometry_msgs]
path = "/opt/ros/humble/share/geometry_msgs/rust"

[patch.crates-io.actionlib_msgs]
path = "/opt/ros/humble/share/actionlib_msgs/rust"

[patch.crates-io.std_msgs]
path = "/opt/ros/humble/share/std_msgs/rust"

[patch.crates-io.statistics_msgs]
path = "/opt/ros/humble/share/statistics_msgs/rust"

[patch.crates-io.examples_rclrs_message_demo]
path = "/opt/ros2_rust_ws/install/examples_rclrs_message_demo/share/examples_rclrs_message_demo/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "/opt/ros2_rust_ws/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"

[patch.crates-io.rclrs]
path = "/opt/ros2_rust_ws/install/rclrs/share/rclrs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/opt/ros/humble/share/rosgraph_msgs/rust"

[patch.crates-io.rclrs_example_msgs]
path = "/opt/ros2_rust_ws/install/rclrs_example_msgs/share/rclrs_example_msgs/rust"

[patch.crates-io.composition_interfaces]
path = "/opt/ros/humble/share/composition_interfaces/rust"

[patch.crates-io.rcl_interfaces]
path = "/opt/ros/humble/share/rcl_interfaces/rust"

[patch.crates-io.lifecycle_msgs]
path = "/opt/ros/humble/share/lifecycle_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "/opt/ros/humble/share/builtin_interfaces/rust"

[patch.crates-io.rosbag2_interfaces]
path = "/opt/ros/humble/share/rosbag2_interfaces/rust"

[patch.crates-io.nav2_msgs]
path = "/opt/ros/humble/share/nav2_msgs/rust"

[patch.crates-io.map_msgs]
path = "/opt/ros/humble/share/map_msgs/rust"

[patch.crates-io.tf2_msgs]
path = "/opt/ros/humble/share/tf2_msgs/rust"

[patch.crates-io.pcl_msgs]
path = "/opt/ros/humble/share/pcl_msgs/rust"

[patch.crates-io.rmw_dds_common]
path = "/opt/ros/humble/share/rmw_dds_common/rust"
